### ISSUE TITLE
How to write a thesis with R Markdown	

### ISSUE THREAD

**Issue by pkra** [HackyHour/Goettingen#9]
Just to fix links on https://hackyhour.github.io/Goettingen/

**Comment by aleimba** [comment]
Thanks for the fix! The "discussion" issues for the HackyHour (HH) sessions are getting confusing, because we're using the issue system also for "real" issues ...

But actually, we don't need an issue for every HH, the pads should suffice. It's just an additional system where people can ask questions etc. before an event ... I'm removing wrong links from the homepage now.

**Comment by pkra** [comment]
Thanks, @aleimba.
